export let names: string[] = [
    "Gruff",
    "Thorin",
    "Balthazar",
    "Gimli",
    "Hammersmith",
    "Rocksteady",
    "Forge",
    "Boulder",
    "Stout",
    "Orebeard",
    "Ironfoot",
    "Nugget",
    "Granite",
    "Stonehelm",
    "Hammerstone",
    "Copperbeard",
    "Flintlock",
    "Stonewall",
    "Ironclad",
    "Durin"
];

export let characteristics: string[] = [
    "the Mighty",
    "the Resilient",
    "the Stalwart",
    "the Stout-hearted",
    "the Unbreakable",
    "the Steadfast",
    "the Indomitable",
    "the Tenacious",
    "the Valiant",
    "the Fearless",
    "the Dauntless",
    "the Unyielding",
    "the Formidable",
    "the Invincible",
    "the Relentless",
    "the Courageous",
    "the Undaunted",
    "the Resolute",
    "the Legendary"
];